DROP TABLE  tbl_candidate;
DROP TABLE  tbl_electoral_periphery;
DROP TABLE  tbl_political_party;
DROP TABLE  tbl_vote;
CREATE TABLE tbl_candidate (pk_candidate_id bigint GENERATED BY DEFAULT AS IDENTITY, fld_surname varchar(50) NOT NULL, fld_name varchar(30) NOT NULL, fk_political_party_id integer NOT NULL, fk_electoral_periphery_id integer NOT NULL, PRIMARY KEY (pk_candidate_id));

CREATE  TABLE  tbl_electoral_periphery  (pk_electoral_periphery_id  integer  GENERATED  BY DEFAULT  AS IDENTITY,   fld_name   varchar(100)   NOT  NULL,   fld_registered_citizens_count   integer,   fld_seats_count integer, PRIMARY KEY (pk_electoral_periphery_id));

CREATE  TABLE  tbl_political_party  (pk_party_id  integer  GENERATED  BY  DEFAULT  AS IDENTITY,  fld_title varchar(50) NOT NULL, fld_leaderFullName varchar(30) NOT NULL, PRIMARY KEY (pk_party_id));

CREATE TABLE tbl_vote (pk_vote_id bigint GENERATED BY DEFAULT AS IDENTITY, fld_is_invalid boolean NOT NULL, fld_is_blank boolean NOT NULL, fk_electoral_periphery_id integer NOT NULL, fk_political_party_id integer, fk_candidate_id bigint, PRIMARY KEY (pk_vote_id));

ALTER TABLE tbl_vote ADD CONSTRAINT FKtbl_vote800602  FOREIGN KEY (fk_candidate_id)  REFERENCES tbl_candidate (pk_candidate_id);

ALTER   TABLE   tbl_vote   ADD   CONSTRAINT   FKtbl_vote929198    FOREIGN   KEY   (fk_political_party_id) REFERENCES tbl_political_party (pk_party_id); 

ALTER  TABLE  tbl_vote  ADD  CONSTRAINT  FKtbl_vote92695   FOREIGN  KEY  (fk_electoral_periphery_id) REFERENCES tbl_electoral_periphery (pk_electoral_periphery_id);

ALTER TABLE tbl_candidate  ADD CONSTRAINT  FKtbl_candid239676  FOREIGN  KEY (fk_political_party_id) REFERENCES tbl_political_party (pk_party_id);

ALTER TABLE tbl_candidate ADD CONSTRAINT FKtbl_politi112723 FOREIGN KEY (fk_electoral_periphery_id) REFERENCES tbl_electoral_periphery (pk_electoral_periphery_id);
